[tool.poetry]
name = "lightkurve"
version = "0.2.0"
description = "A friendly package for analysing TESS & Kepler time series data"
authors = ["TESS Science Support Center <tesshelp@bigbang.gsfc.nasa.gov>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9"
astropy = "^6.0.0"
numpy = "^1.26.3"
matplotlib = "^3.8.2"
sphinx-gallery = "^0.15.0"
nbformat = "^5.9.2"
astropy-sphinx-theme = "^1.1"
rich = "^13.7.0"
astroquery = "^0.4.6"
pandas = "^2.1.4"


[tool.poetry.group.dev.dependencies]
sphinx-astropy = "^1.9.1"
sphinx = "^7.2.6"
sphinx-autobuild = "^2021.3.14"
pydata-sphinx-theme = "^0.15.1"
sphinx-copybutton = "^0.5.2"
nbsphinx = "^0.9.3"
ruff = "^0.1.13"
mypy = "^1.8.0"
pre-commit = "^3.6.0"
pytest = "^7.4.4"
coverage = {version = "^7.4.0", extras = ["toml"]}
bump2version = "^1.0.1"
sphinx-autodoc-typehints = "^1.25.2"
jupyter = "^1.0.0"
line-profiler = "^4.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.coverage.run]
relative_files = true