"""Classes and tools for creating data bundles and batches"""
# from collections.abc import Iterable
# from copy import deepcopy
# from functools import singledispatchmethod
# from textwrap import dedent
from typing import Union

# from warnings import warn
from astropy.io import fits
from astropy.time import Time
from astropy.units import Quantity
from astropy.wcs import WCS

import numpy as np

from .datacube import DataCube, ErrorCube

# from .dataframe import DataFrame, ErrorFrame
# from .dataseries import DataSeries, ErrorSeries
from .dataset import DataSet


# Current TPF ext 1 =
#   array = ['TIME', 'TIMECORR', 'CADENCENO', 'QUALITY','POS_CORR1', 'POS_CORR2',]
#   cube  = ['RAW_CNTS', 'FLUX', 'FLUX_ERR', 'FLUX_BKG', 'FLUX_BKG_ERR']
# Current TPF ext 3
#   ['CADENCENO','RAWX','RAWY','COSMIC_RAY']
class TargetPixelFile(DataSet):
    """Abstract class representing FITS files that contain time series image data

    Not intended to be used directly;
    See KeplerTargetPixelFIle and TessTargetPixelFile instead

    """

    def __init__(
        self,
        path: Union[str, fits.HDUList],
        quality_bitmask: str = "default",
        *args,
        **kwargs,
    ):
        self.path = path
        self.quality_bitmask = quality_bitmask

        if isinstance(path, fits.HDUList):
            hdu = path
        elif isinstance(path, str) and path.startswith("s3://"):
            # Filename is an S3 cloud URI
            hdu = fits.open(
                path, use_fsspec=True, fsspec_kwargs={"anon": True}, **kwargs
            )
        else:
            hdu = fits.open(self.path, **kwargs)

        try:
            # NOT ALL HLSPS HAVE THESE, SO WE'LL NEED A SETUP FILE FOR THOSE?
            # Can check the file provenance in the header, but do all HLSPs use that?
            self.primary_header = hdu[0].header
            self.hdu1_header = hdu[1].header
            self.hdu2_header = hdu[2].header
            self.hdu3_header = hdu[3].header

            # NOTE: I added .astype(float) because if I didn't I got the error
            #       ValueError: Big-endian buffer not supported on little-endian compiler
            if self.primary_header["ORIGIN"] == "NASA/Ames":
                cube_dict = {
                    "RAW_CNTS": hdu[1].data["RAW_CNTS"].astype(float),
                    "FLUX": hdu[1].data["FLUX"].astype(float),
                    "FLUX_BKG": hdu[1].data["FLUX_BKG"].astype(float),
                    # What are row/col_indices?? How to implement?
                    # Probably give it a row/col dictionary that arrays based on origin from header
                }
                err_cube_dict = {
                    "FLUX_ERR": hdu[1].data["FLUX_ERR"].astype(float),
                    "FLUX_BKG_ERR": hdu[1].data["FLUX_BKG_ERR"].astype(float),
                }
                time_dict = {
                    "TIME": hdu[1].data["TIME"].astype(float),
                    "TIMECORR": hdu[1].data["TIMECORR"].astype(float),
                    "CADENCENO": hdu[1].data["CADENCENO"].astype(float),
                    "POS_CORR1": hdu[1].data["POS_CORR1"].astype(float),
                    "POS_CORR2": hdu[1].data["POS_CORR2"].astype(float),
                }
                flux_cube = self._prepare_cubes(cube_dict["FLUX"], time_dict)
                flux_err_cube = self._prepare_err_cubes(
                    err_cube_dict["FLUX_ERR"], time_dict
                )
                self.data_cubes = DataSet(
                    {"FLUX": flux_cube},
                    {"FLUX_ERR": flux_err_cube},
                )

                # What to do with Quality?

                # If there is a cosmic ray extension, make a CR cube?
                # This would have ['CADENCENO','RAWX','RAWY','COSMIC_RAY']

                # What to do with WCS information?

            hdu.close()

        except Exception as e:
            # Cannot instantiate TargetPixelFile, close the HDU to release the file handle
            hdu.close()
            raise e

        # Define here things we know TPFs must have, even if they are generated by users.
        # Flux, flux error, time, etc
        # self.cube = self._prepare_cubes(*kwargs)
        # Some extra things that are optional could still be captured by "args"

    def _prepare_cubes(self, flux, time_cube):
        # TODO: expand to add other items to time dictionaries?

        return DataCube(
            flux,
            time_indices=time_cube,
            # row_indices={"pixel_row": self.row},
            # col_indices={"pixel_column": self.col},
            # exposure_time = exposure,
        )

    def _prepare_err_cubes(self, flux_err, time_cube):
        return ErrorCube(
            flux_err,
            time_indices=time_cube,
            # row_indices={"pixel_row": self.row},
            # col_indices={"pixel_column": self.col},
        )

        # ADD CR CUBE
        # ADD WCS CUBE

    def spatial_bin(self, binsize: Union[int, tuple] = 1):
        """
        Spatially bin the TPF.

        Parameters
        ----------
        binsize :
            the number of pixels to combine. Providing an int assumes the same in both dimensions

        SHOULD THIS RETURN A CUBE, OR REPOPULATE ALL OF THE HEADER INFO?
        """
        # AttributeError: 'DataSet' object has no attribute 'spatial_downsample'
        return self.data_cube.spatial_downsample(binsize)

    def __repr__(self):
        ...

    # def __get_item(self, key):

    # What properties do TPFs have, always?

    @property
    def len(self):
        ...

    @property
    def ra(self):
        """Right Ascension of target ('RA_OBJ' header keyword)."""
        return self.get_keyword("RA_OBJ")

    @property
    def dec(self):
        """Declination of target ('DEC_OBJ' header keyword)."""
        return self.get_keyword("DEC_OBJ")

    # The TargetPixelFile row/col is differant than the DataCube one...
    @property
    def row(self):
        """CCD pixel row number ('2CRV5P' header keyword)."""
        return self.get_keyword("2CRV5P", ext=1, fill_value=0)

    @property
    def column(self):
        """CCD pixel column number ('1CRV5P' header keyword)."""
        return self.get_keyword("1CRV5P", ext=1, fill_value=0)

    @property
    def pos_corr1(self):
        """Returns the column position correction."""
        return self.hdu[1].data["POS_CORR1"][self.quality_mask]

    @property
    def pos_corr2(self):
        """Returns the row position correction."""
        return self.hdu[1].data["POS_CORR2"][self.quality_mask]

    @property
    def pipeline_mask(self):
        """Returns the aperture mask used by the pipeline.

        If the aperture extension is missing from the file, a mask
        composed of all `True` values will be returned.
        """
        # Both Kepler and TESS flag the pixels in the optimal aperture using
        # bit number 2 in the aperture mask extension, e.g. see Section 6 of
        # the TESS Data Products documentation (EXP-TESS-ARC-ICD-TM-0014.pdf).
        try:
            return self.hdu[2].data & 2 > 0
        except (IndexError, TypeError):
            # `IndexError` may be raised if the aperture extension (#2) is missing
            # `TypeError` may be raised because early versions of TESScut returned floats in HDU 2
            return np.ones(self.hdu[1].data["FLUX"][0].shape, dtype=bool)

    @property
    def shape(self):
        """Return the cube dimension shape."""
        return self.flux.shape

    @property
    def time(self) -> Time:
        """Returns the time for all good-quality cadences."""
        time_values = self.flux_cube.btjd[self.quality_mask]
        # Some data products have missing time values;
        # we need to set these to zero or `Time` cannot be instantiated.
        time_values[~np.isfinite(time_values)] = 0

        bjdrefi = self.hdu1_header["BJDREFI"]
        if bjdrefi == 2454833:
            time_format = "bkjd"
        elif bjdrefi == 2457000:
            time_format = "btjd"
        else:
            time_format = "jd"

        return Time(
            time_values,
            scale=self.hdu1_header.get("TIMESYS", "tdb").lower(),
            format=time_format,
        )

    @property
    def cadenceno(self):
        """Return the cadence number for all good-quality cadences."""
        cadenceno = self.hdu[1].data["CADENCENO"][self.quality_mask]
        # The TESScut service returns an array of zeros as CADENCENO.
        # If this is the case, return frame numbers from 0 instead.
        if cadenceno[0] == 0:
            return np.arange(0, len(cadenceno), 1, dtype=int)
        return cadenceno

    @property
    def nan_time_mask(self):
        """Returns a boolean mask flagging cadences whose time is `nan`."""
        return self.time.value == 0

    @property
    def flux(self) -> Quantity:
        """Returns the flux for all good-quality cadences."""
        unit = None
        if self.get_header(ext=1).get("TUNIT5") == "e-/s":
            unit = "electron/s"
        return Quantity(self.hdu[1].data["FLUX"][self.quality_mask], unit=unit)

    @property
    def flux_err(self) -> Quantity:
        """Returns the flux uncertainty for all good-quality cadences."""
        unit = None
        if self.get_header(ext=1).get("TUNIT6") == "e-/s":
            unit = "electron/s"
        return Quantity(self.hdu[1].data["FLUX_ERR"][self.quality_mask], unit=unit)

    @property
    def flux_bkg(self) -> Quantity:
        """Returns the background flux for all good-quality cadences."""
        return Quantity(
            self.hdu[1].data["FLUX_BKG"][self.quality_mask], unit="electron/s"
        )

    @property
    def flux_bkg_err(self) -> Quantity:
        return Quantity(
            self.hdu[1].data["FLUX_BKG_ERR"][self.quality_mask], unit="electron/s"
        )

    @property
    def quality(self):
        """Returns the quality flag integer of every good cadence."""
        return self.hdu[1].data["QUALITY"][self.quality_mask]

    @property
    def wcs(self) -> WCS:
        """Returns an `astropy.wcs.WCS` object with the World Coordinate System
        solution for the target pixel file.

        Returns
        -------
        w : `astropy.wcs.WCS` object
            WCS solution
        """
        if "MAST" in self.hdu[0].header["ORIGIN"]:  # Is it a TessCut TPF?
            # TPF's generated using the TESSCut service in early 2019 only appear
            # to contain a valid WCS in the second extension (the aperture
            # extension), so we treat such files as a special case.
            return WCS(self.hdu[2])
        else:
            # For standard (Ames-pipeline-produced) TPF files, we use the WCS
            # keywords provided in the first extension (the data table extension).
            # Specifically, we use the WCS keywords for the 5th data column (FLUX).
            wcs_keywords = {
                "1CTYP5": "CTYPE1",
                "2CTYP5": "CTYPE2",
                "1CRPX5": "CRPIX1",
                "2CRPX5": "CRPIX2",
                "1CRVL5": "CRVAL1",
                "2CRVL5": "CRVAL2",
                "1CUNI5": "CUNIT1",
                "2CUNI5": "CUNIT2",
                "1CDLT5": "CDELT1",
                "2CDLT5": "CDELT2",
                "11PC5": "PC1_1",
                "12PC5": "PC1_2",
                "21PC5": "PC2_1",
                "22PC5": "PC2_2",
                "NAXIS1": "NAXIS1",
                "NAXIS2": "NAXIS2",
            }
            mywcs = {}
            for oldkey, newkey in wcs_keywords.items():
                if self.hdu[1].header.get(oldkey, None) is not None:
                    mywcs[newkey] = self.hdu[1].header[oldkey]
            return WCS(mywcs)

    # What are the key methods that a TPF needs?
    # These can be lifted from lightkurve and made to work within the new framework

    def get_coordinates():
        ...

    def get_header(self, ext: int = 0):
        """Returns the metadata embedded in the file.

        Target Pixel Files contain embedded metadata headers spread across three
        different FITS extensions:

        1. The "PRIMARY" extension (``ext=0``) provides a metadata header
           providing details on the target and its CCD position.
        2. The "PIXELS" extension (``ext=1``) provides details on the
           data column and their coordinate system (WCS).
        3. The "APERTURE" extension (``ext=2``) provides details on the
           aperture pixel mask and the expected coordinate system (WCS).
        4. The "TARGET COSMIC RAY" extension (``ext=3``) provides the cosmic
           ray values removed from each pixel and cadence.
           Only populated for 20 second data products.

        Parameters
        ----------
        ext : int or str
            FITS extension name or number.

        Returns
        -------
        header : `~astropy.io.fits.header.Header`
            Header object containing metadata keywords.
        """
        if ext == 0:
            return self.primary_header
        else:
            return getattr(self, f"hdu{ext}_header")
        # return self.hdu[ext].header

    def get_keyword(self, keyword, ext=0, fill_value=None):
        """Returns a header keyword value.

        If the keyword is Undefined or does not exist,
        then return ``fill_value`` instead.
        """
        return self.get_header(ext).get(keyword, fill_value)

    def to_lightcurve(self, method="sap", corrector=None, **kwargs):
        # This should be made much easier by the lkdata framework!
        ...
        # data: Union[List, np.ndarray],
        # time_indices: Union[Dict, List, None] = None,
        # row_indices: Union[Dict, List, None] = None,
        # col_indices: Union[Dict, List, None] = None,

    def estimate_centroids(self):
        ...

    def plot(self):
        ...

    def create_threshold_mask(self):
        ...

    def estimate_background(self, aperture_mask="background"):
        ...

    def query_solar_system_objects(self):
        ...

    def cutout(self):
        ...


class KeplerTargetPixelFile(TargetPixelFile):
    """Class to read and interact with the pixel data products
    ("Target Pixel Files") created by NASA's Kepler pipeline.

    This class offers a user-friendly way to open a Kepler Target Pixel File
    (TPF), access its meta data, visualize its contents, extract light curves
    with custom aperture masks, estimate centroid positions, and more.


    Parameters
    ----------
    path : str or `~astropy.io.fits.HDUList`
        Path to a Kepler Target Pixel file. Alternatively, you can pass a
        `.HDUList` object, which is the AstroPy object returned by
        the `astropy.io.fits.open` function.
    quality_bitmask : "none", "default", "hard", "hardest", or int
        Bitmask that should be used to ignore bad-quality cadences.
        If a string is passed, it has the following meaning:

            * "none": no cadences will be ignored (equivalent to
              ``quality_bitmask=0``).
            * "default": cadences with severe quality issues will be ignored
              (equivalent to ``quality_bitmask=1130799``).
            * "hard": more conservative choice of flags to ignore
              (equivalent to ``quality_bitmask=1664431``).
              This is known to remove good data.
            * "hardest": remove all cadences that have one or more flags raised
              (equivalent to ``quality_bitmask=2096639``). This mask is not
              recommended because some quality flags can safely be ignored.

        If an integer is passed, it will be used as a bitmask, i.e. it will
        have the effect of removing cadences where
        ``(tpf.hdu[1].data['QUALITY'] & quality_bitmask) > 0``.
        See the :class:`KeplerQualityFlags` class for details on the bitmasks.
    **kwargs : dict
        Optional keyword arguments passed on to `astropy.io.fits.open`.

    References
    ----------
    .. [1] Kepler: A Search for Terrestrial Planets. Kepler Archive Manual.
        http://archive.stsci.edu/kepler/manuals/archive_manual.pdf
    """

    '''def __init__(self, path, quality_bitmask="default", **kwargs):
        super(KeplerTargetPixelFile, self).__init__(
            path, quality_bitmask=quality_bitmask, **kwargs
        )
        try:
            self.quality_mask = KeplerQualityFlags.create_quality_mask(
                quality_array=self.hdu[1].data["QUALITY"], bitmask=quality_bitmask
            )

            # check to make sure the correct filetype has been provided
            filetype = detect_filetype(self.hdu)
            if filetype == "TessTargetPixelFile":
                warnings.warn(
                    "A TESS data product is being opened using the "
                    "`KeplerTargetPixelFile` class. "
                    "Please use `TessTargetPixelFile` instead.",
                    LightkurveWarning,
                )
            elif filetype is None:
                warnings.warn(
                    "File header not recognized as Kepler or TESS " "observation.",
                    LightkurveWarning,
                )

            # Use the KEPLERID keyword as the default targetid
            if self.targetid is None:
                self.targetid = self.get_header().get("KEPLERID")
        except Exception as e:
            # Cannot instantiate TargetPixelFile, close the HDU to release the file handle
            self.hdu.close()
            raise e

    def __repr__(self):
        return "KeplerTargetPixelFile Object (ID: {})".format(self.targetid)

    @property
    def module(self):
        """Kepler CCD module number. ('MODULE' header keyword)"""
        return self.get_keyword("MODULE")

    @property
    def output(self):
        """Kepler CCD module output number. ('OUTPUT' header keyword)"""
        return self.get_keyword("OUTPUT")

    @property
    def channel(self):
        """Kepler CCD channel number. ('CHANNEL' header keyword)"""
        return self.get_keyword("CHANNEL")

    @property
    def quarter(self):
        """Kepler quarter number. ('QUARTER' header keyword)"""
        return self.get_keyword("QUARTER")

    @property
    def campaign(self):
        """K2 Campaign number. ('CAMPAIGN' header keyword)"""
        return self.get_keyword("CAMPAIGN")

    @property
    def mission(self):
        """'Kepler' or 'K2'. ('MISSION' header keyword)"""
        return self.get_keyword("MISSION")'''
